-- Auto-generated from the v4 Apps Script seed tables. Do not hand-edit;
-- corrections belong in the app, which writes back to these tables.

INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES
  ('hb', 'Haemoglobin', 'Haemoglobin', 'g/dL', 'seed'),
  ('hgb', 'Haemoglobin', 'Haemoglobin', 'g/dL', 'seed'),
  ('hemoglobin', 'Haemoglobin', 'Haemoglobin', 'g/dL', 'seed'),
  ('haemoglobin', 'Haemoglobin', 'Haemoglobin', 'g/dL', 'seed'),
  ('hemoglobinhb', 'Haemoglobin', 'Haemoglobin', 'g/dL', 'seed'),
  ('haemoglobinhb', 'Haemoglobin', 'Haemoglobin', 'g/dL', 'seed'),
  ('bloodhemoglobin', 'Haemoglobin', 'Haemoglobin', 'g/dL', 'seed'),
  ('tlc', 'Total WBC Count', 'Total WBC Count', '/µL', 'seed'),
  ('totalleucocytecount', 'Total WBC Count', 'Total WBC Count', '/µL', 'seed'),
  ('totalleukocytecount', 'Total WBC Count', 'Total WBC Count', '/µL', 'seed'),
  ('wbc', 'Total WBC Count', 'Total WBC Count', '/µL', 'seed'),
  ('wbccount', 'Total WBC Count', 'Total WBC Count', '/µL', 'seed'),
  ('totalwbccount', 'Total WBC Count', 'Total WBC Count', '/µL', 'seed'),
  ('leucocytecount', 'Total WBC Count', 'Total WBC Count', '/µL', 'seed'),
  ('plateletcount', 'Platelet Count', 'Platelet Count', '/µL', 'seed'),
  ('platelets', 'Platelet Count', 'Platelet Count', '/µL', 'seed'),
  ('plt', 'Platelet Count', 'Platelet Count', '/µL', 'seed'),
  ('rbccount', 'RBC Count', 'RBC Count', 'million/µL', 'seed'),
  ('totalrbccount', 'RBC Count', 'RBC Count', 'million/µL', 'seed'),
  ('redbloodcellcount', 'RBC Count', 'RBC Count', 'million/µL', 'seed'),
  ('pcv', 'Haematocrit (PCV)', 'Haematocrit (PCV)', '%', 'seed'),
  ('hct', 'Haematocrit (PCV)', 'Haematocrit (PCV)', '%', 'seed'),
  ('haematocrit', 'Haematocrit (PCV)', 'Haematocrit (PCV)', '%', 'seed'),
  ('hematocrit', 'Haematocrit (PCV)', 'Haematocrit (PCV)', '%', 'seed'),
  ('packedcellvolume', 'Haematocrit (PCV)', 'Haematocrit (PCV)', '%', 'seed'),
  ('mcv', 'MCV', 'MCV', 'fL', 'seed'),
  ('meancorpuscularvolume', 'MCV', 'MCV', 'fL', 'seed'),
  ('mch', 'MCH', 'MCH', 'pg', 'seed'),
  ('mchc', 'MCHC', 'MCHC', 'g/dL', 'seed'),
  ('rdw', 'RDW', 'RDW', '%', 'seed'),
  ('rdwcv', 'RDW', 'RDW', '%', 'seed'),
  ('esr', 'ESR', 'ESR', 'mm/hr', 'seed'),
  ('erythrocytesedimentationrate', 'ESR', 'ESR', 'mm/hr', 'seed'),
  ('neutrophils', 'Neutrophils %', 'Neutrophils %', '%', 'seed'),
  ('neutrophil', 'Neutrophils %', 'Neutrophils %', '%', 'seed'),
  ('polymorphs', 'Neutrophils %', 'Neutrophils %', '%', 'seed'),
  ('lymphocytes', 'Lymphocytes %', 'Lymphocytes %', '%', 'seed'),
  ('lymphocyte', 'Lymphocytes %', 'Lymphocytes %', '%', 'seed'),
  ('eosinophils', 'Eosinophils %', 'Eosinophils %', '%', 'seed'),
  ('monocytes', 'Monocytes %', 'Monocytes %', '%', 'seed'),
  ('basophils', 'Basophils %', 'Basophils %', '%', 'seed'),
  ('anc', 'Absolute Neutrophil Count', 'Absolute Neutrophil Count', '/µL', 'seed'),
  ('absoluteneutrophilcount', 'Absolute Neutrophil Count', 'Absolute Neutrophil Count', '/µL', 'seed'),
  ('alc', 'Absolute Lymphocyte Count', 'Absolute Lymphocyte Count', '/µL', 'seed'),
  ('absolutelymphocytecount', 'Absolute Lymphocyte Count', 'Absolute Lymphocyte Count', '/µL', 'seed'),
  ('fbs', 'Fasting Blood Sugar', 'Fasting Blood Sugar', 'mg/dL', 'seed'),
  ('fastingbloodsugar', 'Fasting Blood Sugar', 'Fasting Blood Sugar', 'mg/dL', 'seed'),
  ('fastingglucose', 'Fasting Blood Sugar', 'Fasting Blood Sugar', 'mg/dL', 'seed'),
  ('glucosefasting', 'Fasting Blood Sugar', 'Fasting Blood Sugar', 'mg/dL', 'seed'),
  ('bloodglucosefasting', 'Fasting Blood Sugar', 'Fasting Blood Sugar', 'mg/dL', 'seed'),
  ('fastingplasmaglucose', 'Fasting Blood Sugar', 'Fasting Blood Sugar', 'mg/dL', 'seed'),
  ('fpg', 'Fasting Blood Sugar', 'Fasting Blood Sugar', 'mg/dL', 'seed'),
  ('sugarfasting', 'Fasting Blood Sugar', 'Fasting Blood Sugar', 'mg/dL', 'seed'),
  ('ppbs', 'Post Meal Blood Sugar', 'Post Meal Blood Sugar', 'mg/dL', 'seed'),
  ('pp2bs', 'Post Meal Blood Sugar', 'Post Meal Blood Sugar', 'mg/dL', 'seed'),
  ('postmealbloodsugar', 'Post Meal Blood Sugar', 'Post Meal Blood Sugar', 'mg/dL', 'seed'),
  ('postprandialbloodsugar', 'Post Meal Blood Sugar', 'Post Meal Blood Sugar', 'mg/dL', 'seed'),
  ('glucosepostprandial', 'Post Meal Blood Sugar', 'Post Meal Blood Sugar', 'mg/dL', 'seed'),
  ('bloodglucosepp', 'Post Meal Blood Sugar', 'Post Meal Blood Sugar', 'mg/dL', 'seed'),
  ('sugarpp', 'Post Meal Blood Sugar', 'Post Meal Blood Sugar', 'mg/dL', 'seed'),
  ('glucosepp', 'Post Meal Blood Sugar', 'Post Meal Blood Sugar', 'mg/dL', 'seed'),
  ('rbs', 'Random Blood Sugar', 'Random Blood Sugar', 'mg/dL', 'seed'),
  ('randombloodsugar', 'Random Blood Sugar', 'Random Blood Sugar', 'mg/dL', 'seed'),
  ('randomglucose', 'Random Blood Sugar', 'Random Blood Sugar', 'mg/dL', 'seed'),
  ('glucoserandom', 'Random Blood Sugar', 'Random Blood Sugar', 'mg/dL', 'seed'),
  ('hba1c', 'HbA1c', 'HbA1c', '%', 'seed'),
  ('hb1ac', 'HbA1c', 'HbA1c', '%', 'seed'),
  ('glycatedhemoglobin', 'HbA1c', 'HbA1c', '%', 'seed'),
  ('glycosylatedhemoglobin', 'HbA1c', 'HbA1c', '%', 'seed'),
  ('glycatedhaemoglobinhba1c', 'HbA1c', 'HbA1c', '%', 'seed'),
  ('a1c', 'HbA1c', 'HbA1c', '%', 'seed'),
  ('eag', 'Estimated Average Glucose', 'Estimated Average Glucose', 'mg/dL', 'seed'),
  ('estimatedaverageglucose', 'Estimated Average Glucose', 'Estimated Average Glucose', 'mg/dL', 'seed'),
  ('totalcholesterol', 'Total Cholesterol', 'Total Cholesterol', 'mg/dL', 'seed'),
  ('cholesteroltotal', 'Total Cholesterol', 'Total Cholesterol', 'mg/dL', 'seed'),
  ('serumcholesterol', 'Total Cholesterol', 'Total Cholesterol', 'mg/dL', 'seed'),
  ('cholesterol', 'Total Cholesterol', 'Total Cholesterol', 'mg/dL', 'seed'),
  ('hdl', 'HDL Cholesterol', 'HDL Cholesterol', 'mg/dL', 'seed'),
  ('hdlcholesterol', 'HDL Cholesterol', 'HDL Cholesterol', 'mg/dL', 'seed'),
  ('cholesterolhdl', 'HDL Cholesterol', 'HDL Cholesterol', 'mg/dL', 'seed'),
  ('hdlc', 'HDL Cholesterol', 'HDL Cholesterol', 'mg/dL', 'seed'),
  ('ldl', 'LDL Cholesterol', 'LDL Cholesterol', 'mg/dL', 'seed'),
  ('ldlcholesterol', 'LDL Cholesterol', 'LDL Cholesterol', 'mg/dL', 'seed'),
  ('cholesterolldl', 'LDL Cholesterol', 'LDL Cholesterol', 'mg/dL', 'seed'),
  ('ldlcalculated', 'LDL Cholesterol', 'LDL Cholesterol', 'mg/dL', 'seed'),
  ('ldlc', 'LDL Cholesterol', 'LDL Cholesterol', 'mg/dL', 'seed'),
  ('vldl', 'VLDL Cholesterol', 'VLDL Cholesterol', 'mg/dL', 'seed'),
  ('vldlcholesterol', 'VLDL Cholesterol', 'VLDL Cholesterol', 'mg/dL', 'seed'),
  ('triglycerides', 'Triglycerides', 'Triglycerides', 'mg/dL', 'seed'),
  ('tg', 'Triglycerides', 'Triglycerides', 'mg/dL', 'seed'),
  ('serumtriglycerides', 'Triglycerides', 'Triglycerides', 'mg/dL', 'seed'),
  ('triglyceride', 'Triglycerides', 'Triglycerides', 'mg/dL', 'seed'),
  ('nonhdlcholesterol', 'Non-HDL Cholesterol', 'Non-HDL Cholesterol', 'mg/dL', 'seed'),
  ('cholhdlratio', 'Cholesterol / HDL Ratio', 'Cholesterol / HDL Ratio', '', 'seed'),
  ('totalcholesterolhdlratio', 'Cholesterol / HDL Ratio', 'Cholesterol / HDL Ratio', '', 'seed'),
  ('urea', 'Urea', 'Urea', 'mg/dL', 'seed'),
  ('bloodurea', 'Urea', 'Urea', 'mg/dL', 'seed'),
  ('serumurea', 'Urea', 'Urea', 'mg/dL', 'seed'),
  ('bun', 'Blood Urea Nitrogen', 'Blood Urea Nitrogen', 'mg/dL', 'seed'),
  ('bloodureanitrogen', 'Blood Urea Nitrogen', 'Blood Urea Nitrogen', 'mg/dL', 'seed'),
  ('creatinine', 'Creatinine', 'Creatinine', 'mg/dL', 'seed'),
  ('serumcreatinine', 'Creatinine', 'Creatinine', 'mg/dL', 'seed'),
  ('creatinineserum', 'Creatinine', 'Creatinine', 'mg/dL', 'seed'),
  ('egfr', 'eGFR', 'eGFR', 'mL/min/1.73m²', 'seed'),
  ('estimatedgfr', 'eGFR', 'eGFR', 'mL/min/1.73m²', 'seed'),
  ('uricacid', 'Uric Acid', 'Uric Acid', 'mg/dL', 'seed'),
  ('serumuricacid', 'Uric Acid', 'Uric Acid', 'mg/dL', 'seed'),
  ('sodium', 'Sodium', 'Sodium', 'mmol/L', 'seed'),
  ('serumsodium', 'Sodium', 'Sodium', 'mmol/L', 'seed'),
  ('na', 'Sodium', 'Sodium', 'mmol/L', 'seed'),
  ('potassium', 'Potassium', 'Potassium', 'mmol/L', 'seed'),
  ('serumpotassium', 'Potassium', 'Potassium', 'mmol/L', 'seed'),
  ('k', 'Potassium', 'Potassium', 'mmol/L', 'seed'),
  ('chloride', 'Chloride', 'Chloride', 'mmol/L', 'seed'),
  ('serumchloride', 'Chloride', 'Chloride', 'mmol/L', 'seed'),
  ('calcium', 'Calcium', 'Calcium', 'mg/dL', 'seed'),
  ('serumcalcium', 'Calcium', 'Calcium', 'mg/dL', 'seed'),
  ('totalcalcium', 'Calcium', 'Calcium', 'mg/dL', 'seed'),
  ('phosphorus', 'Phosphorus', 'Phosphorus', 'mg/dL', 'seed'),
  ('serumphosphorus', 'Phosphorus', 'Phosphorus', 'mg/dL', 'seed'),
  ('magnesium', 'Magnesium', 'Magnesium', 'mg/dL', 'seed'),
  ('totalbilirubin', 'Total Bilirubin', 'Total Bilirubin', 'mg/dL', 'seed'),
  ('bilirubintotal', 'Total Bilirubin', 'Total Bilirubin', 'mg/dL', 'seed'),
  ('serumbilirubintotal', 'Total Bilirubin', 'Total Bilirubin', 'mg/dL', 'seed'),
  ('directbilirubin', 'Direct Bilirubin', 'Direct Bilirubin', 'mg/dL', 'seed'),
  ('bilirubindirect', 'Direct Bilirubin', 'Direct Bilirubin', 'mg/dL', 'seed'),
  ('conjugatedbilirubin', 'Direct Bilirubin', 'Direct Bilirubin', 'mg/dL', 'seed'),
  ('indirectbilirubin', 'Indirect Bilirubin', 'Indirect Bilirubin', 'mg/dL', 'seed'),
  ('bilirubinindirect', 'Indirect Bilirubin', 'Indirect Bilirubin', 'mg/dL', 'seed'),
  ('alt', 'ALT (SGPT)', 'ALT (SGPT)', 'U/L', 'seed'),
  ('sgpt', 'ALT (SGPT)', 'ALT (SGPT)', 'U/L', 'seed'),
  ('altsgpt', 'ALT (SGPT)', 'ALT (SGPT)', 'U/L', 'seed'),
  ('sgptalt', 'ALT (SGPT)', 'ALT (SGPT)', 'U/L', 'seed'),
  ('alanineaminotransferase', 'ALT (SGPT)', 'ALT (SGPT)', 'U/L', 'seed'),
  ('alaninetransaminase', 'ALT (SGPT)', 'ALT (SGPT)', 'U/L', 'seed'),
  ('ast', 'AST (SGOT)', 'AST (SGOT)', 'U/L', 'seed'),
  ('sgot', 'AST (SGOT)', 'AST (SGOT)', 'U/L', 'seed'),
  ('astsgot', 'AST (SGOT)', 'AST (SGOT)', 'U/L', 'seed'),
  ('sgotast', 'AST (SGOT)', 'AST (SGOT)', 'U/L', 'seed'),
  ('aspartateaminotransferase', 'AST (SGOT)', 'AST (SGOT)', 'U/L', 'seed'),
  ('aspartatetransaminase', 'AST (SGOT)', 'AST (SGOT)', 'U/L', 'seed'),
  ('alp', 'Alkaline Phosphatase', 'Alkaline Phosphatase', 'U/L', 'seed'),
  ('alkalinephosphatase', 'Alkaline Phosphatase', 'Alkaline Phosphatase', 'U/L', 'seed'),
  ('serumalkalinephosphatase', 'Alkaline Phosphatase', 'Alkaline Phosphatase', 'U/L', 'seed'),
  ('ggt', 'GGT', 'GGT', 'U/L', 'seed'),
  ('gammagt', 'GGT', 'GGT', 'U/L', 'seed'),
  ('gammaglutamyltransferase', 'GGT', 'GGT', 'U/L', 'seed'),
  ('totalprotein', 'Total Protein', 'Total Protein', 'g/dL', 'seed'),
  ('serumtotalprotein', 'Total Protein', 'Total Protein', 'g/dL', 'seed'),
  ('proteintotal', 'Total Protein', 'Total Protein', 'g/dL', 'seed'),
  ('albumin', 'Albumin', 'Albumin', 'g/dL', 'seed'),
  ('serumalbumin', 'Albumin', 'Albumin', 'g/dL', 'seed'),
  ('globulin', 'Globulin', 'Globulin', 'g/dL', 'seed'),
  ('agratio', 'A/G Ratio', 'A/G Ratio', '', 'seed'),
  ('albuminglobulinratio', 'A/G Ratio', 'A/G Ratio', '', 'seed'),
  ('tsh', 'TSH', 'TSH', 'µIU/mL', 'seed'),
  ('thyroidstimulatinghormone', 'TSH', 'TSH', 'µIU/mL', 'seed'),
  ('serumtsh', 'TSH', 'TSH', 'µIU/mL', 'seed'),
  ('tshultrasensitive', 'TSH', 'TSH', 'µIU/mL', 'seed'),
  ('ft3', 'Free T3', 'Free T3', 'pg/mL', 'seed'),
  ('freet3', 'Free T3', 'Free T3', 'pg/mL', 'seed'),
  ('freetriiodothyronine', 'Free T3', 'Free T3', 'pg/mL', 'seed'),
  ('ft4', 'Free T4', 'Free T4', 'ng/dL', 'seed'),
  ('freet4', 'Free T4', 'Free T4', 'ng/dL', 'seed'),
  ('freethyroxine', 'Free T4', 'Free T4', 'ng/dL', 'seed'),
  ('t3', 'Total T3', 'Total T3', 'ng/dL', 'seed'),
  ('totalt3', 'Total T3', 'Total T3', 'ng/dL', 'seed'),
  ('triiodothyronine', 'Total T3', 'Total T3', 'ng/dL', 'seed'),
  ('t4', 'Total T4', 'Total T4', 'µg/dL', 'seed'),
  ('totalt4', 'Total T4', 'Total T4', 'µg/dL', 'seed'),
  ('thyroxine', 'Total T4', 'Total T4', 'µg/dL', 'seed'),
  ('antitpo', 'Anti-TPO Antibody', 'Anti-TPO Antibody', 'IU/mL', 'seed'),
  ('antitpoantibody', 'Anti-TPO Antibody', 'Anti-TPO Antibody', 'IU/mL', 'seed'),
  ('thyroidperoxidaseantibody', 'Anti-TPO Antibody', 'Anti-TPO Antibody', 'IU/mL', 'seed'),
  ('vitamind', 'Vitamin D', 'Vitamin D', 'ng/mL', 'seed'),
  ('vitamind3', 'Vitamin D', 'Vitamin D', 'ng/mL', 'seed'),
  ('vitd', 'Vitamin D', 'Vitamin D', 'ng/mL', 'seed'),
  ('vitd3', 'Vitamin D', 'Vitamin D', 'ng/mL', 'seed'),
  ('25hydroxyvitamind', 'Vitamin D', 'Vitamin D', 'ng/mL', 'seed'),
  ('vitamind25hydroxy', 'Vitamin D', 'Vitamin D', 'ng/mL', 'seed'),
  ('vitamindtotal', 'Vitamin D', 'Vitamin D', 'ng/mL', 'seed'),
  ('vitaminb12', 'Vitamin B12', 'Vitamin B12', 'pg/mL', 'seed'),
  ('vitb12', 'Vitamin B12', 'Vitamin B12', 'pg/mL', 'seed'),
  ('b12', 'Vitamin B12', 'Vitamin B12', 'pg/mL', 'seed'),
  ('cyanocobalamin', 'Vitamin B12', 'Vitamin B12', 'pg/mL', 'seed'),
  ('serumvitaminb12', 'Vitamin B12', 'Vitamin B12', 'pg/mL', 'seed'),
  ('folate', 'Folate', 'Folate', 'ng/mL', 'seed'),
  ('folicacid', 'Folate', 'Folate', 'ng/mL', 'seed'),
  ('serumfolate', 'Folate', 'Folate', 'ng/mL', 'seed'),
  ('ferritin', 'Ferritin', 'Ferritin', 'ng/mL', 'seed'),
  ('serumferritin', 'Ferritin', 'Ferritin', 'ng/mL', 'seed'),
  ('iron', 'Serum Iron', 'Serum Iron', 'µg/dL', 'seed'),
  ('serumiron', 'Serum Iron', 'Serum Iron', 'µg/dL', 'seed'),
  ('tibc', 'TIBC', 'TIBC', 'µg/dL', 'seed'),
  ('totalironbindingcapacity', 'TIBC', 'TIBC', 'µg/dL', 'seed'),
  ('transferrinsaturation', 'Transferrin Saturation', 'Transferrin Saturation', '%', 'seed'),
  ('tsat', 'Transferrin Saturation', 'Transferrin Saturation', '%', 'seed'),
  ('crp', 'CRP', 'CRP', 'mg/L', 'seed'),
  ('creactiveprotein', 'CRP', 'CRP', 'mg/L', 'seed'),
  ('hscrp', 'hs-CRP', 'hs-CRP', 'mg/L', 'seed'),
  ('highsensitivitycrp', 'hs-CRP', 'hs-CRP', 'mg/L', 'seed'),
  ('ddimer', 'D-Dimer', 'D-Dimer', 'ng/mL', 'seed'),
  ('procalcitonin', 'Procalcitonin', 'Procalcitonin', 'ng/mL', 'seed'),
  ('psa', 'PSA', 'PSA', 'ng/mL', 'seed'),
  ('prostatespecificantigen', 'PSA', 'PSA', 'ng/mL', 'seed'),
  ('totalpsa', 'PSA', 'PSA', 'ng/mL', 'seed'),
  ('testosterone', 'Testosterone', 'Testosterone', 'ng/dL', 'seed'),
  ('totaltestosterone', 'Testosterone', 'Testosterone', 'ng/dL', 'seed'),
  ('cortisol', 'Cortisol', 'Cortisol', 'µg/dL', 'seed'),
  ('prolactin', 'Prolactin', 'Prolactin', 'ng/mL', 'seed'),
  ('bp', 'Blood Pressure', 'Blood Pressure', 'mmHg', 'seed'),
  ('bloodpressure', 'Blood Pressure', 'Blood Pressure', 'mmHg', 'seed'),
  ('bloodpressuresystolicdiastolic', 'Blood Pressure', 'Blood Pressure', 'mmHg', 'seed'),
  ('bpsystolicdiastolic', 'Blood Pressure', 'Blood Pressure', 'mmHg', 'seed'),
  ('pulse', 'Pulse', 'Pulse', 'bpm', 'seed'),
  ('pulserate', 'Pulse', 'Pulse', 'bpm', 'seed'),
  ('heartrate', 'Pulse', 'Pulse', 'bpm', 'seed'),
  ('hr', 'Pulse', 'Pulse', 'bpm', 'seed'),
  ('spo2', 'SpO2', 'SpO2', '%', 'seed'),
  ('oxygensaturation', 'SpO2', 'SpO2', '%', 'seed'),
  ('o2saturation', 'SpO2', 'SpO2', '%', 'seed'),
  ('saturation', 'SpO2', 'SpO2', '%', 'seed'),
  ('sao2', 'SpO2', 'SpO2', '%', 'seed'),
  ('temperature', 'Temperature', 'Temperature', '°C', 'seed'),
  ('bodytemperature', 'Temperature', 'Temperature', '°C', 'seed'),
  ('temp', 'Temperature', 'Temperature', '°C', 'seed'),
  ('weight', 'Weight', 'Weight', 'kg', 'seed'),
  ('bodyweight', 'Weight', 'Weight', 'kg', 'seed'),
  ('height', 'Height', 'Height', 'cm', 'seed'),
  ('bmi', 'BMI', 'BMI', 'kg/m²', 'seed'),
  ('bodymassindex', 'BMI', 'BMI', 'kg/m²', 'seed'),
  ('respiratoryrate', 'Respiratory Rate', 'Respiratory Rate', 'breaths/min', 'seed'),
  ('rr', 'Respiratory Rate', 'Respiratory Rate', 'breaths/min', 'seed'),
  ('waistcircumference', 'Waist Circumference', 'Waist Circumference', 'cm', 'seed'),
  ('waist', 'Waist Circumference', 'Waist Circumference', 'cm', 'seed'),
  ('urineprotein', 'Urine Protein', 'Urine Protein', '', 'seed'),
  ('urinesugar', 'Urine Sugar', 'Urine Sugar', '', 'seed'),
  ('urineph', 'Urine pH', 'Urine pH', '', 'seed'),
  ('urinespecificgravity', 'Urine Specific Gravity', 'Urine Specific Gravity', '', 'seed'),
  ('puscells', 'Urine Pus Cells', 'Urine Pus Cells', '/hpf', 'seed'),
  ('urinepuscells', 'Urine Pus Cells', 'Urine Pus Cells', '/hpf', 'seed');

INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES
  ('Haemoglobin', 'gl', 'g/dL', 0.1, 0),
  ('Haemoglobin', 'gmdl', 'g/dL', 1, 0),
  ('Haemoglobin', 'gm', 'g/dL', 1, 0),
  ('Haemoglobin', 'gpercent', 'g/dL', 1, 0),
  ('Total WBC Count', '109l', '/µL', 1000, 0),
  ('Total WBC Count', '103ul', '/µL', 1000, 0),
  ('Total WBC Count', 'cumm', '/µL', 1, 0),
  ('Total WBC Count', 'cellscumm', '/µL', 1, 0),
  ('Total WBC Count', 'ul', '/µL', 1, 0),
  ('Platelet Count', '109l', '/µL', 1000, 0),
  ('Platelet Count', '103ul', '/µL', 1000, 0),
  ('Platelet Count', 'cumm', '/µL', 1, 0),
  ('Platelet Count', 'lakhcumm', '/µL', 100000, 0),
  ('Platelet Count', 'ul', '/µL', 1, 0),
  ('RBC Count', '1012l', 'million/µL', 1, 0),
  ('RBC Count', '106ul', 'million/µL', 1, 0),
  ('RBC Count', 'millioncumm', 'million/µL', 1, 0),
  ('Fasting Blood Sugar', 'mmoll', 'mg/dL', 18.0182, 0),
  ('Post Meal Blood Sugar', 'mmoll', 'mg/dL', 18.0182, 0),
  ('Random Blood Sugar', 'mmoll', 'mg/dL', 18.0182, 0),
  ('Total Cholesterol', 'mmoll', 'mg/dL', 38.67, 0),
  ('HDL Cholesterol', 'mmoll', 'mg/dL', 38.67, 0),
  ('LDL Cholesterol', 'mmoll', 'mg/dL', 38.67, 0),
  ('VLDL Cholesterol', 'mmoll', 'mg/dL', 38.67, 0),
  ('Triglycerides', 'mmoll', 'mg/dL', 88.57, 0),
  ('Creatinine', 'umoll', 'mg/dL', 0.0113, 0),
  ('Creatinine', 'molL', 'mg/dL', 0.0113, 0),
  ('Urea', 'mmoll', 'mg/dL', 6.006, 0),
  ('Uric Acid', 'umoll', 'mg/dL', 0.0168, 0),
  ('Calcium', 'mmoll', 'mg/dL', 4.008, 0),
  ('Total Bilirubin', 'umoll', 'mg/dL', 0.0585, 0),
  ('Direct Bilirubin', 'umoll', 'mg/dL', 0.0585, 0),
  ('Indirect Bilirubin', 'umoll', 'mg/dL', 0.0585, 0),
  ('Vitamin D', 'nmoll', 'ng/mL', 0.4, 0),
  ('Vitamin B12', 'pmoll', 'pg/mL', 1.355, 0),
  ('Folate', 'nmoll', 'ng/mL', 0.4413, 0),
  ('Serum Iron', 'umoll', 'µg/dL', 5.587, 0),
  ('TIBC', 'umoll', 'µg/dL', 5.587, 0),
  ('TSH', 'miuL', 'µIU/mL', 1, 0),
  ('TSH', 'uiuml', 'µIU/mL', 1, 0),
  ('TSH', 'miul', 'µIU/mL', 1, 0),
  ('TSH', 'iuml', 'µIU/mL', 1, 0),
  ('Free T4', 'pmoll', 'ng/dL', 0.0777, 0),
  ('Free T3', 'pmoll', 'pg/mL', 0.651, 0),
  ('CRP', 'mgdl', 'mg/L', 10, 0),
  ('hs-CRP', 'mgdl', 'mg/L', 10, 0),
  ('Temperature', 'f', '°C', 0.5556, -17.7778),
  ('Temperature', 'degf', '°C', 0.5556, -17.7778),
  ('Temperature', 'fahrenheit', '°C', 0.5556, -17.7778),
  ('Weight', 'lb', 'kg', 0.4536, 0),
  ('Weight', 'lbs', 'kg', 0.4536, 0),
  ('Weight', 'pounds', 'kg', 0.4536, 0),
  ('Height', 'in', 'cm', 2.54, 0),
  ('Height', 'inch', 'cm', 2.54, 0),
  ('Height', 'inches', 'cm', 2.54, 0),
  ('Height', 'ft', 'cm', 30.48, 0),
  ('Total Protein', 'gl', 'g/dL', 0.1, 0),
  ('Albumin', 'gl', 'g/dL', 0.1, 0),
  ('Globulin', 'gl', 'g/dL', 0.1, 0);

INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES
  ('Haemoglobin', 'm', 18, 200, 13, 17, 'g/dL'),
  ('Haemoglobin', 'f', 18, 200, 12, 15, 'g/dL'),
  ('Total WBC Count', 'any', 18, 200, 4000, 11000, '/µL'),
  ('Platelet Count', 'any', 18, 200, 150000, 410000, '/µL'),
  ('Fasting Blood Sugar', 'any', 18, 200, 70, 100, 'mg/dL'),
  ('Post Meal Blood Sugar', 'any', 18, 200, 70, 140, 'mg/dL'),
  ('HbA1c', 'any', 18, 200, NULL, 5.7, '%'),
  ('Total Cholesterol', 'any', 18, 200, NULL, 200, 'mg/dL'),
  ('LDL Cholesterol', 'any', 18, 200, NULL, 100, 'mg/dL'),
  ('HDL Cholesterol', 'm', 18, 200, 40, NULL, 'mg/dL'),
  ('HDL Cholesterol', 'f', 18, 200, 50, NULL, 'mg/dL'),
  ('Triglycerides', 'any', 18, 200, NULL, 150, 'mg/dL'),
  ('Creatinine', 'm', 18, 200, 0.7, 1.3, 'mg/dL'),
  ('Creatinine', 'f', 18, 200, 0.6, 1.1, 'mg/dL'),
  ('Urea', 'any', 18, 200, 15, 40, 'mg/dL'),
  ('Uric Acid', 'm', 18, 200, 3.5, 7.2, 'mg/dL'),
  ('Uric Acid', 'f', 18, 200, 2.6, 6, 'mg/dL'),
  ('TSH', 'any', 18, 200, 0.4, 4, 'µIU/mL'),
  ('Free T4', 'any', 18, 200, 0.8, 1.8, 'ng/dL'),
  ('Free T3', 'any', 18, 200, 2.3, 4.2, 'pg/mL'),
  ('Vitamin D', 'any', 18, 200, 30, 100, 'ng/mL'),
  ('Vitamin B12', 'any', 18, 200, 200, 900, 'pg/mL'),
  ('Ferritin', 'm', 18, 200, 30, 400, 'ng/mL'),
  ('Ferritin', 'f', 18, 200, 15, 150, 'ng/mL'),
  ('ALT (SGPT)', 'any', 18, 200, NULL, 50, 'U/L'),
  ('AST (SGOT)', 'any', 18, 200, NULL, 50, 'U/L'),
  ('Total Bilirubin', 'any', 18, 200, 0.2, 1.2, 'mg/dL'),
  ('Albumin', 'any', 18, 200, 3.5, 5.2, 'g/dL'),
  ('Sodium', 'any', 18, 200, 135, 145, 'mmol/L'),
  ('Potassium', 'any', 18, 200, 3.5, 5.1, 'mmol/L'),
  ('Blood Pressure', 'any', 18, 200, NULL, 130, 'mmHg'),
  ('SpO2', 'any', 0, 200, 95, 100, '%'),
  ('BMI', 'any', 18, 200, 18.5, 24.9, 'kg/m²');
