-- Auto-generated from the v4 Apps Script seed tables.
-- One statement per row: D1 rejects multi-row VALUES lists as compound SELECTs.

INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('hb', 'Haemoglobin', 'Haemoglobin', 'g/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('hgb', 'Haemoglobin', 'Haemoglobin', 'g/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('hemoglobin', 'Haemoglobin', 'Haemoglobin', 'g/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('haemoglobin', 'Haemoglobin', 'Haemoglobin', 'g/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('hemoglobinhb', 'Haemoglobin', 'Haemoglobin', 'g/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('haemoglobinhb', 'Haemoglobin', 'Haemoglobin', 'g/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('bloodhemoglobin', 'Haemoglobin', 'Haemoglobin', 'g/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('tlc', 'Total WBC Count', 'Total WBC Count', '/µL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('totalleucocytecount', 'Total WBC Count', 'Total WBC Count', '/µL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('totalleukocytecount', 'Total WBC Count', 'Total WBC Count', '/µL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('wbc', 'Total WBC Count', 'Total WBC Count', '/µL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('wbccount', 'Total WBC Count', 'Total WBC Count', '/µL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('totalwbccount', 'Total WBC Count', 'Total WBC Count', '/µL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('leucocytecount', 'Total WBC Count', 'Total WBC Count', '/µL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('plateletcount', 'Platelet Count', 'Platelet Count', '/µL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('platelets', 'Platelet Count', 'Platelet Count', '/µL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('plt', 'Platelet Count', 'Platelet Count', '/µL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('rbccount', 'RBC Count', 'RBC Count', 'million/µL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('totalrbccount', 'RBC Count', 'RBC Count', 'million/µL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('redbloodcellcount', 'RBC Count', 'RBC Count', 'million/µL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('pcv', 'Haematocrit (PCV)', 'Haematocrit (PCV)', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('hct', 'Haematocrit (PCV)', 'Haematocrit (PCV)', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('haematocrit', 'Haematocrit (PCV)', 'Haematocrit (PCV)', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('hematocrit', 'Haematocrit (PCV)', 'Haematocrit (PCV)', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('packedcellvolume', 'Haematocrit (PCV)', 'Haematocrit (PCV)', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('mcv', 'MCV', 'MCV', 'fL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('meancorpuscularvolume', 'MCV', 'MCV', 'fL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('mch', 'MCH', 'MCH', 'pg', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('mchc', 'MCHC', 'MCHC', 'g/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('rdw', 'RDW', 'RDW', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('rdwcv', 'RDW', 'RDW', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('esr', 'ESR', 'ESR', 'mm/hr', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('erythrocytesedimentationrate', 'ESR', 'ESR', 'mm/hr', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('neutrophils', 'Neutrophils %', 'Neutrophils %', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('neutrophil', 'Neutrophils %', 'Neutrophils %', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('polymorphs', 'Neutrophils %', 'Neutrophils %', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('lymphocytes', 'Lymphocytes %', 'Lymphocytes %', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('lymphocyte', 'Lymphocytes %', 'Lymphocytes %', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('eosinophils', 'Eosinophils %', 'Eosinophils %', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('monocytes', 'Monocytes %', 'Monocytes %', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('basophils', 'Basophils %', 'Basophils %', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('anc', 'Absolute Neutrophil Count', 'Absolute Neutrophil Count', '/µL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('absoluteneutrophilcount', 'Absolute Neutrophil Count', 'Absolute Neutrophil Count', '/µL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('alc', 'Absolute Lymphocyte Count', 'Absolute Lymphocyte Count', '/µL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('absolutelymphocytecount', 'Absolute Lymphocyte Count', 'Absolute Lymphocyte Count', '/µL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('fbs', 'Fasting Blood Sugar', 'Fasting Blood Sugar', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('fastingbloodsugar', 'Fasting Blood Sugar', 'Fasting Blood Sugar', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('fastingglucose', 'Fasting Blood Sugar', 'Fasting Blood Sugar', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('glucosefasting', 'Fasting Blood Sugar', 'Fasting Blood Sugar', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('bloodglucosefasting', 'Fasting Blood Sugar', 'Fasting Blood Sugar', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('fastingplasmaglucose', 'Fasting Blood Sugar', 'Fasting Blood Sugar', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('fpg', 'Fasting Blood Sugar', 'Fasting Blood Sugar', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('sugarfasting', 'Fasting Blood Sugar', 'Fasting Blood Sugar', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('ppbs', 'Post Meal Blood Sugar', 'Post Meal Blood Sugar', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('pp2bs', 'Post Meal Blood Sugar', 'Post Meal Blood Sugar', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('postmealbloodsugar', 'Post Meal Blood Sugar', 'Post Meal Blood Sugar', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('postprandialbloodsugar', 'Post Meal Blood Sugar', 'Post Meal Blood Sugar', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('glucosepostprandial', 'Post Meal Blood Sugar', 'Post Meal Blood Sugar', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('bloodglucosepp', 'Post Meal Blood Sugar', 'Post Meal Blood Sugar', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('sugarpp', 'Post Meal Blood Sugar', 'Post Meal Blood Sugar', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('glucosepp', 'Post Meal Blood Sugar', 'Post Meal Blood Sugar', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('rbs', 'Random Blood Sugar', 'Random Blood Sugar', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('randombloodsugar', 'Random Blood Sugar', 'Random Blood Sugar', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('randomglucose', 'Random Blood Sugar', 'Random Blood Sugar', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('glucoserandom', 'Random Blood Sugar', 'Random Blood Sugar', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('hba1c', 'HbA1c', 'HbA1c', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('hb1ac', 'HbA1c', 'HbA1c', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('glycatedhemoglobin', 'HbA1c', 'HbA1c', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('glycosylatedhemoglobin', 'HbA1c', 'HbA1c', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('glycatedhaemoglobinhba1c', 'HbA1c', 'HbA1c', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('a1c', 'HbA1c', 'HbA1c', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('eag', 'Estimated Average Glucose', 'Estimated Average Glucose', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('estimatedaverageglucose', 'Estimated Average Glucose', 'Estimated Average Glucose', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('totalcholesterol', 'Total Cholesterol', 'Total Cholesterol', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('cholesteroltotal', 'Total Cholesterol', 'Total Cholesterol', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('serumcholesterol', 'Total Cholesterol', 'Total Cholesterol', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('cholesterol', 'Total Cholesterol', 'Total Cholesterol', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('hdl', 'HDL Cholesterol', 'HDL Cholesterol', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('hdlcholesterol', 'HDL Cholesterol', 'HDL Cholesterol', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('cholesterolhdl', 'HDL Cholesterol', 'HDL Cholesterol', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('hdlc', 'HDL Cholesterol', 'HDL Cholesterol', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('ldl', 'LDL Cholesterol', 'LDL Cholesterol', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('ldlcholesterol', 'LDL Cholesterol', 'LDL Cholesterol', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('cholesterolldl', 'LDL Cholesterol', 'LDL Cholesterol', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('ldlcalculated', 'LDL Cholesterol', 'LDL Cholesterol', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('ldlc', 'LDL Cholesterol', 'LDL Cholesterol', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('vldl', 'VLDL Cholesterol', 'VLDL Cholesterol', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('vldlcholesterol', 'VLDL Cholesterol', 'VLDL Cholesterol', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('triglycerides', 'Triglycerides', 'Triglycerides', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('tg', 'Triglycerides', 'Triglycerides', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('serumtriglycerides', 'Triglycerides', 'Triglycerides', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('triglyceride', 'Triglycerides', 'Triglycerides', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('nonhdlcholesterol', 'Non-HDL Cholesterol', 'Non-HDL Cholesterol', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('cholhdlratio', 'Cholesterol / HDL Ratio', 'Cholesterol / HDL Ratio', '', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('totalcholesterolhdlratio', 'Cholesterol / HDL Ratio', 'Cholesterol / HDL Ratio', '', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('urea', 'Urea', 'Urea', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('bloodurea', 'Urea', 'Urea', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('serumurea', 'Urea', 'Urea', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('bun', 'Blood Urea Nitrogen', 'Blood Urea Nitrogen', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('bloodureanitrogen', 'Blood Urea Nitrogen', 'Blood Urea Nitrogen', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('creatinine', 'Creatinine', 'Creatinine', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('serumcreatinine', 'Creatinine', 'Creatinine', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('creatinineserum', 'Creatinine', 'Creatinine', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('egfr', 'eGFR', 'eGFR', 'mL/min/1.73m²', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('estimatedgfr', 'eGFR', 'eGFR', 'mL/min/1.73m²', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('uricacid', 'Uric Acid', 'Uric Acid', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('serumuricacid', 'Uric Acid', 'Uric Acid', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('sodium', 'Sodium', 'Sodium', 'mmol/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('serumsodium', 'Sodium', 'Sodium', 'mmol/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('na', 'Sodium', 'Sodium', 'mmol/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('potassium', 'Potassium', 'Potassium', 'mmol/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('serumpotassium', 'Potassium', 'Potassium', 'mmol/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('k', 'Potassium', 'Potassium', 'mmol/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('chloride', 'Chloride', 'Chloride', 'mmol/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('serumchloride', 'Chloride', 'Chloride', 'mmol/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('calcium', 'Calcium', 'Calcium', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('serumcalcium', 'Calcium', 'Calcium', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('totalcalcium', 'Calcium', 'Calcium', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('phosphorus', 'Phosphorus', 'Phosphorus', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('serumphosphorus', 'Phosphorus', 'Phosphorus', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('magnesium', 'Magnesium', 'Magnesium', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('totalbilirubin', 'Total Bilirubin', 'Total Bilirubin', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('bilirubintotal', 'Total Bilirubin', 'Total Bilirubin', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('serumbilirubintotal', 'Total Bilirubin', 'Total Bilirubin', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('directbilirubin', 'Direct Bilirubin', 'Direct Bilirubin', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('bilirubindirect', 'Direct Bilirubin', 'Direct Bilirubin', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('conjugatedbilirubin', 'Direct Bilirubin', 'Direct Bilirubin', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('indirectbilirubin', 'Indirect Bilirubin', 'Indirect Bilirubin', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('bilirubinindirect', 'Indirect Bilirubin', 'Indirect Bilirubin', 'mg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('alt', 'ALT (SGPT)', 'ALT (SGPT)', 'U/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('sgpt', 'ALT (SGPT)', 'ALT (SGPT)', 'U/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('altsgpt', 'ALT (SGPT)', 'ALT (SGPT)', 'U/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('sgptalt', 'ALT (SGPT)', 'ALT (SGPT)', 'U/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('alanineaminotransferase', 'ALT (SGPT)', 'ALT (SGPT)', 'U/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('alaninetransaminase', 'ALT (SGPT)', 'ALT (SGPT)', 'U/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('ast', 'AST (SGOT)', 'AST (SGOT)', 'U/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('sgot', 'AST (SGOT)', 'AST (SGOT)', 'U/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('astsgot', 'AST (SGOT)', 'AST (SGOT)', 'U/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('sgotast', 'AST (SGOT)', 'AST (SGOT)', 'U/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('aspartateaminotransferase', 'AST (SGOT)', 'AST (SGOT)', 'U/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('aspartatetransaminase', 'AST (SGOT)', 'AST (SGOT)', 'U/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('alp', 'Alkaline Phosphatase', 'Alkaline Phosphatase', 'U/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('alkalinephosphatase', 'Alkaline Phosphatase', 'Alkaline Phosphatase', 'U/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('serumalkalinephosphatase', 'Alkaline Phosphatase', 'Alkaline Phosphatase', 'U/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('ggt', 'GGT', 'GGT', 'U/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('gammagt', 'GGT', 'GGT', 'U/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('gammaglutamyltransferase', 'GGT', 'GGT', 'U/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('totalprotein', 'Total Protein', 'Total Protein', 'g/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('serumtotalprotein', 'Total Protein', 'Total Protein', 'g/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('proteintotal', 'Total Protein', 'Total Protein', 'g/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('albumin', 'Albumin', 'Albumin', 'g/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('serumalbumin', 'Albumin', 'Albumin', 'g/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('globulin', 'Globulin', 'Globulin', 'g/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('agratio', 'A/G Ratio', 'A/G Ratio', '', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('albuminglobulinratio', 'A/G Ratio', 'A/G Ratio', '', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('tsh', 'TSH', 'TSH', 'µIU/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('thyroidstimulatinghormone', 'TSH', 'TSH', 'µIU/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('serumtsh', 'TSH', 'TSH', 'µIU/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('tshultrasensitive', 'TSH', 'TSH', 'µIU/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('ft3', 'Free T3', 'Free T3', 'pg/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('freet3', 'Free T3', 'Free T3', 'pg/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('freetriiodothyronine', 'Free T3', 'Free T3', 'pg/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('ft4', 'Free T4', 'Free T4', 'ng/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('freet4', 'Free T4', 'Free T4', 'ng/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('freethyroxine', 'Free T4', 'Free T4', 'ng/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('t3', 'Total T3', 'Total T3', 'ng/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('totalt3', 'Total T3', 'Total T3', 'ng/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('triiodothyronine', 'Total T3', 'Total T3', 'ng/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('t4', 'Total T4', 'Total T4', 'µg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('totalt4', 'Total T4', 'Total T4', 'µg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('thyroxine', 'Total T4', 'Total T4', 'µg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('antitpo', 'Anti-TPO Antibody', 'Anti-TPO Antibody', 'IU/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('antitpoantibody', 'Anti-TPO Antibody', 'Anti-TPO Antibody', 'IU/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('thyroidperoxidaseantibody', 'Anti-TPO Antibody', 'Anti-TPO Antibody', 'IU/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('vitamind', 'Vitamin D', 'Vitamin D', 'ng/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('vitamind3', 'Vitamin D', 'Vitamin D', 'ng/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('vitd', 'Vitamin D', 'Vitamin D', 'ng/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('vitd3', 'Vitamin D', 'Vitamin D', 'ng/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('25hydroxyvitamind', 'Vitamin D', 'Vitamin D', 'ng/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('vitamind25hydroxy', 'Vitamin D', 'Vitamin D', 'ng/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('vitamindtotal', 'Vitamin D', 'Vitamin D', 'ng/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('vitaminb12', 'Vitamin B12', 'Vitamin B12', 'pg/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('vitb12', 'Vitamin B12', 'Vitamin B12', 'pg/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('b12', 'Vitamin B12', 'Vitamin B12', 'pg/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('cyanocobalamin', 'Vitamin B12', 'Vitamin B12', 'pg/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('serumvitaminb12', 'Vitamin B12', 'Vitamin B12', 'pg/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('folate', 'Folate', 'Folate', 'ng/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('folicacid', 'Folate', 'Folate', 'ng/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('serumfolate', 'Folate', 'Folate', 'ng/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('ferritin', 'Ferritin', 'Ferritin', 'ng/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('serumferritin', 'Ferritin', 'Ferritin', 'ng/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('iron', 'Serum Iron', 'Serum Iron', 'µg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('serumiron', 'Serum Iron', 'Serum Iron', 'µg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('tibc', 'TIBC', 'TIBC', 'µg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('totalironbindingcapacity', 'TIBC', 'TIBC', 'µg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('transferrinsaturation', 'Transferrin Saturation', 'Transferrin Saturation', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('tsat', 'Transferrin Saturation', 'Transferrin Saturation', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('crp', 'CRP', 'CRP', 'mg/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('creactiveprotein', 'CRP', 'CRP', 'mg/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('hscrp', 'hs-CRP', 'hs-CRP', 'mg/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('highsensitivitycrp', 'hs-CRP', 'hs-CRP', 'mg/L', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('ddimer', 'D-Dimer', 'D-Dimer', 'ng/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('procalcitonin', 'Procalcitonin', 'Procalcitonin', 'ng/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('psa', 'PSA', 'PSA', 'ng/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('prostatespecificantigen', 'PSA', 'PSA', 'ng/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('totalpsa', 'PSA', 'PSA', 'ng/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('testosterone', 'Testosterone', 'Testosterone', 'ng/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('totaltestosterone', 'Testosterone', 'Testosterone', 'ng/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('cortisol', 'Cortisol', 'Cortisol', 'µg/dL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('prolactin', 'Prolactin', 'Prolactin', 'ng/mL', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('bp', 'Blood Pressure', 'Blood Pressure', 'mmHg', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('bloodpressure', 'Blood Pressure', 'Blood Pressure', 'mmHg', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('bloodpressuresystolicdiastolic', 'Blood Pressure', 'Blood Pressure', 'mmHg', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('bpsystolicdiastolic', 'Blood Pressure', 'Blood Pressure', 'mmHg', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('pulse', 'Pulse', 'Pulse', 'bpm', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('pulserate', 'Pulse', 'Pulse', 'bpm', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('heartrate', 'Pulse', 'Pulse', 'bpm', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('hr', 'Pulse', 'Pulse', 'bpm', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('spo2', 'SpO2', 'SpO2', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('oxygensaturation', 'SpO2', 'SpO2', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('o2saturation', 'SpO2', 'SpO2', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('saturation', 'SpO2', 'SpO2', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('sao2', 'SpO2', 'SpO2', '%', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('temperature', 'Temperature', 'Temperature', '°C', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('bodytemperature', 'Temperature', 'Temperature', '°C', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('temp', 'Temperature', 'Temperature', '°C', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('weight', 'Weight', 'Weight', 'kg', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('bodyweight', 'Weight', 'Weight', 'kg', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('height', 'Height', 'Height', 'cm', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('bmi', 'BMI', 'BMI', 'kg/m²', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('bodymassindex', 'BMI', 'BMI', 'kg/m²', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('respiratoryrate', 'Respiratory Rate', 'Respiratory Rate', 'breaths/min', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('rr', 'Respiratory Rate', 'Respiratory Rate', 'breaths/min', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('waistcircumference', 'Waist Circumference', 'Waist Circumference', 'cm', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('waist', 'Waist Circumference', 'Waist Circumference', 'cm', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('urineprotein', 'Urine Protein', 'Urine Protein', '', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('urinesugar', 'Urine Sugar', 'Urine Sugar', '', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('urineph', 'Urine pH', 'Urine pH', '', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('urinespecificgravity', 'Urine Specific Gravity', 'Urine Specific Gravity', '', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('puscells', 'Urine Pus Cells', 'Urine Pus Cells', '/hpf', 'seed');
INSERT OR IGNORE INTO parameter_aliases (alias_key, original, parameter, unit, source) VALUES ('urinepuscells', 'Urine Pus Cells', 'Urine Pus Cells', '/hpf', 'seed');
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Haemoglobin', 'gl', 'g/dL', 0.1, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Haemoglobin', 'gmdl', 'g/dL', 1, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Haemoglobin', 'gm', 'g/dL', 1, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Haemoglobin', 'gpercent', 'g/dL', 1, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Total WBC Count', '109l', '/µL', 1000, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Total WBC Count', '103ul', '/µL', 1000, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Total WBC Count', 'cumm', '/µL', 1, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Total WBC Count', 'cellscumm', '/µL', 1, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Total WBC Count', 'ul', '/µL', 1, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Platelet Count', '109l', '/µL', 1000, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Platelet Count', '103ul', '/µL', 1000, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Platelet Count', 'cumm', '/µL', 1, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Platelet Count', 'lakhcumm', '/µL', 100000, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Platelet Count', 'ul', '/µL', 1, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('RBC Count', '1012l', 'million/µL', 1, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('RBC Count', '106ul', 'million/µL', 1, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('RBC Count', 'millioncumm', 'million/µL', 1, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Fasting Blood Sugar', 'mmoll', 'mg/dL', 18.0182, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Post Meal Blood Sugar', 'mmoll', 'mg/dL', 18.0182, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Random Blood Sugar', 'mmoll', 'mg/dL', 18.0182, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Total Cholesterol', 'mmoll', 'mg/dL', 38.67, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('HDL Cholesterol', 'mmoll', 'mg/dL', 38.67, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('LDL Cholesterol', 'mmoll', 'mg/dL', 38.67, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('VLDL Cholesterol', 'mmoll', 'mg/dL', 38.67, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Triglycerides', 'mmoll', 'mg/dL', 88.57, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Creatinine', 'umoll', 'mg/dL', 0.0113, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Creatinine', 'molL', 'mg/dL', 0.0113, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Urea', 'mmoll', 'mg/dL', 6.006, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Uric Acid', 'umoll', 'mg/dL', 0.0168, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Calcium', 'mmoll', 'mg/dL', 4.008, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Total Bilirubin', 'umoll', 'mg/dL', 0.0585, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Direct Bilirubin', 'umoll', 'mg/dL', 0.0585, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Indirect Bilirubin', 'umoll', 'mg/dL', 0.0585, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Vitamin D', 'nmoll', 'ng/mL', 0.4, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Vitamin B12', 'pmoll', 'pg/mL', 1.355, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Folate', 'nmoll', 'ng/mL', 0.4413, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Serum Iron', 'umoll', 'µg/dL', 5.587, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('TIBC', 'umoll', 'µg/dL', 5.587, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('TSH', 'miuL', 'µIU/mL', 1, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('TSH', 'uiuml', 'µIU/mL', 1, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('TSH', 'miul', 'µIU/mL', 1, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('TSH', 'iuml', 'µIU/mL', 1, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Free T4', 'pmoll', 'ng/dL', 0.0777, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Free T3', 'pmoll', 'pg/mL', 0.651, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('CRP', 'mgdl', 'mg/L', 10, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('hs-CRP', 'mgdl', 'mg/L', 10, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Temperature', 'f', '°C', 0.5556, -17.7778);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Temperature', 'degf', '°C', 0.5556, -17.7778);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Temperature', 'fahrenheit', '°C', 0.5556, -17.7778);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Weight', 'lb', 'kg', 0.4536, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Weight', 'lbs', 'kg', 0.4536, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Weight', 'pounds', 'kg', 0.4536, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Height', 'in', 'cm', 2.54, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Height', 'inch', 'cm', 2.54, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Height', 'inches', 'cm', 2.54, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Height', 'ft', 'cm', 30.48, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Total Protein', 'gl', 'g/dL', 0.1, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Albumin', 'gl', 'g/dL', 0.1, 0);
INSERT OR IGNORE INTO unit_conversions (parameter, from_unit_key, to_unit, multiply_by, add_offset) VALUES ('Globulin', 'gl', 'g/dL', 0.1, 0);
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Haemoglobin', 'm', 18, 200, 13, 17, 'g/dL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Haemoglobin', 'f', 18, 200, 12, 15, 'g/dL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Total WBC Count', 'any', 18, 200, 4000, 11000, '/µL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Platelet Count', 'any', 18, 200, 150000, 410000, '/µL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Fasting Blood Sugar', 'any', 18, 200, 70, 100, 'mg/dL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Post Meal Blood Sugar', 'any', 18, 200, 70, 140, 'mg/dL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('HbA1c', 'any', 18, 200, NULL, 5.7, '%');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Total Cholesterol', 'any', 18, 200, NULL, 200, 'mg/dL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('LDL Cholesterol', 'any', 18, 200, NULL, 100, 'mg/dL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('HDL Cholesterol', 'm', 18, 200, 40, NULL, 'mg/dL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('HDL Cholesterol', 'f', 18, 200, 50, NULL, 'mg/dL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Triglycerides', 'any', 18, 200, NULL, 150, 'mg/dL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Creatinine', 'm', 18, 200, 0.7, 1.3, 'mg/dL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Creatinine', 'f', 18, 200, 0.6, 1.1, 'mg/dL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Urea', 'any', 18, 200, 15, 40, 'mg/dL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Uric Acid', 'm', 18, 200, 3.5, 7.2, 'mg/dL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Uric Acid', 'f', 18, 200, 2.6, 6, 'mg/dL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('TSH', 'any', 18, 200, 0.4, 4, 'µIU/mL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Free T4', 'any', 18, 200, 0.8, 1.8, 'ng/dL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Free T3', 'any', 18, 200, 2.3, 4.2, 'pg/mL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Vitamin D', 'any', 18, 200, 30, 100, 'ng/mL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Vitamin B12', 'any', 18, 200, 200, 900, 'pg/mL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Ferritin', 'm', 18, 200, 30, 400, 'ng/mL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Ferritin', 'f', 18, 200, 15, 150, 'ng/mL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('ALT (SGPT)', 'any', 18, 200, NULL, 50, 'U/L');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('AST (SGOT)', 'any', 18, 200, NULL, 50, 'U/L');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Total Bilirubin', 'any', 18, 200, 0.2, 1.2, 'mg/dL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Albumin', 'any', 18, 200, 3.5, 5.2, 'g/dL');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Sodium', 'any', 18, 200, 135, 145, 'mmol/L');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Potassium', 'any', 18, 200, 3.5, 5.1, 'mmol/L');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('Blood Pressure', 'any', 18, 200, NULL, 130, 'mmHg');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('SpO2', 'any', 0, 200, 95, 100, '%');
INSERT OR IGNORE INTO reference_bands (parameter, sex, age_min, age_max, low, high, unit) VALUES ('BMI', 'any', 18, 200, 18.5, 24.9, 'kg/m²');
